# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: insight.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'insight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinsight.proto\x12\x05proto\".\n\x18GetMonitorInsightRequest\x12\x12\n\nmonitor_id\x18\x01 \x01(\t\"\xd5\x01\n\x0eMonitorInsight\x12\x12\n\nmonitor_id\x18\x01 \x01(\t\x12\x14\n\x0cmonitor_name\x18\x02 \x01(\t\x12\x12\n\nrisk_score\x18\x03 \x01(\x05\x12\x18\n\x10\x61nomaly_detected\x18\x04 \x01(\x08\x12\x10\n\x08severity\x18\x05 \x01(\t\x12\x0f\n\x07summary\x18\x06 \x01(\t\x12\x1a\n\x12recommended_action\x18\x07 \x01(\t\x12\x16\n\x0ehuman_readable\x18\x08 \x01(\t\x12\x14\n\x0cgenerated_at\x18\t \x01(\t\"C\n\x19GetMonitorInsightResponse\x12&\n\x07insight\x18\x01 \x01(\x0b\x32\x15.proto.MonitorInsight2h\n\x0eInsightService\x12V\n\x11GetMonitorInsight\x12\x1f.proto.GetMonitorInsightRequest\x1a .proto.GetMonitorInsightResponseB&Z$github.com/CuesoftCloud/upstat/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'insight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$github.com/CuesoftCloud/upstat/proto'
  _globals['_GETMONITORINSIGHTREQUEST']._serialized_start=24
  _globals['_GETMONITORINSIGHTREQUEST']._serialized_end=70
  _globals['_MONITORINSIGHT']._serialized_start=73
  _globals['_MONITORINSIGHT']._serialized_end=286
  _globals['_GETMONITORINSIGHTRESPONSE']._serialized_start=288
  _globals['_GETMONITORINSIGHTRESPONSE']._serialized_end=355
  _globals['_INSIGHTSERVICE']._serialized_start=357
  _globals['_INSIGHTSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
