// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/insight.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMonitorInsightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorInsightRequest) Reset() {
	*x = GetMonitorInsightRequest{}
	mi := &file_proto_insight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorInsightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorInsightRequest) ProtoMessage() {}

func (x *GetMonitorInsightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorInsightRequest.ProtoReflect.Descriptor instead.
func (*GetMonitorInsightRequest) Descriptor() ([]byte, []int) {
	return file_proto_insight_proto_rawDescGZIP(), []int{0}
}

func (x *GetMonitorInsightRequest) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

type MonitorInsight struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MonitorId         string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	MonitorName       string                 `protobuf:"bytes,2,opt,name=monitor_name,json=monitorName,proto3" json:"monitor_name,omitempty"`
	RiskScore         int32                  `protobuf:"varint,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	AnomalyDetected   bool                   `protobuf:"varint,4,opt,name=anomaly_detected,json=anomalyDetected,proto3" json:"anomaly_detected,omitempty"`
	Severity          string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Summary           string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	RecommendedAction string                 `protobuf:"bytes,7,opt,name=recommended_action,json=recommendedAction,proto3" json:"recommended_action,omitempty"`
	HumanReadable     string                 `protobuf:"bytes,8,opt,name=human_readable,json=humanReadable,proto3" json:"human_readable,omitempty"`
	GeneratedAt       string                 `protobuf:"bytes,9,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MonitorInsight) Reset() {
	*x = MonitorInsight{}
	mi := &file_proto_insight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorInsight) ProtoMessage() {}

func (x *MonitorInsight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorInsight.ProtoReflect.Descriptor instead.
func (*MonitorInsight) Descriptor() ([]byte, []int) {
	return file_proto_insight_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorInsight) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *MonitorInsight) GetMonitorName() string {
	if x != nil {
		return x.MonitorName
	}
	return ""
}

func (x *MonitorInsight) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *MonitorInsight) GetAnomalyDetected() bool {
	if x != nil {
		return x.AnomalyDetected
	}
	return false
}

func (x *MonitorInsight) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *MonitorInsight) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MonitorInsight) GetRecommendedAction() string {
	if x != nil {
		return x.RecommendedAction
	}
	return ""
}

func (x *MonitorInsight) GetHumanReadable() string {
	if x != nil {
		return x.HumanReadable
	}
	return ""
}

func (x *MonitorInsight) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

type GetMonitorInsightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insight       *MonitorInsight        `protobuf:"bytes,1,opt,name=insight,proto3" json:"insight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorInsightResponse) Reset() {
	*x = GetMonitorInsightResponse{}
	mi := &file_proto_insight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorInsightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorInsightResponse) ProtoMessage() {}

func (x *GetMonitorInsightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorInsightResponse.ProtoReflect.Descriptor instead.
func (*GetMonitorInsightResponse) Descriptor() ([]byte, []int) {
	return file_proto_insight_proto_rawDescGZIP(), []int{2}
}

func (x *GetMonitorInsightResponse) GetInsight() *MonitorInsight {
	if x != nil {
		return x.Insight
	}
	return nil
}

var File_proto_insight_proto protoreflect.FileDescriptor

const file_proto_insight_proto_rawDesc = "" +
	"\n" +
	"\x13proto/insight.proto\x12\x05proto\"9\n" +
	"\x18GetMonitorInsightRequest\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\"\xcb\x02\n" +
	"\x0eMonitorInsight\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12!\n" +
	"\fmonitor_name\x18\x02 \x01(\tR\vmonitorName\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x05R\triskScore\x12)\n" +
	"\x10anomaly_detected\x18\x04 \x01(\bR\x0fanomalyDetected\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12-\n" +
	"\x12recommended_action\x18\a \x01(\tR\x11recommendedAction\x12%\n" +
	"\x0ehuman_readable\x18\b \x01(\tR\rhumanReadable\x12!\n" +
	"\fgenerated_at\x18\t \x01(\tR\vgeneratedAt\"L\n" +
	"\x19GetMonitorInsightResponse\x12/\n" +
	"\ainsight\x18\x01 \x01(\v2\x15.proto.MonitorInsightR\ainsight2h\n" +
	"\x0eInsightService\x12V\n" +
	"\x11GetMonitorInsight\x12\x1f.proto.GetMonitorInsightRequest\x1a .proto.GetMonitorInsightResponseB&Z$github.com/CuesoftCloud/upstat/protob\x06proto3"

var (
	file_proto_insight_proto_rawDescOnce sync.Once
	file_proto_insight_proto_rawDescData []byte
)

func file_proto_insight_proto_rawDescGZIP() []byte {
	file_proto_insight_proto_rawDescOnce.Do(func() {
		file_proto_insight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_insight_proto_rawDesc), len(file_proto_insight_proto_rawDesc)))
	})
	return file_proto_insight_proto_rawDescData
}

var file_proto_insight_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_insight_proto_goTypes = []any{
	(*GetMonitorInsightRequest)(nil),  // 0: proto.GetMonitorInsightRequest
	(*MonitorInsight)(nil),            // 1: proto.MonitorInsight
	(*GetMonitorInsightResponse)(nil), // 2: proto.GetMonitorInsightResponse
}
var file_proto_insight_proto_depIdxs = []int32{
	1, // 0: proto.GetMonitorInsightResponse.insight:type_name -> proto.MonitorInsight
	0, // 1: proto.InsightService.GetMonitorInsight:input_type -> proto.GetMonitorInsightRequest
	2, // 2: proto.InsightService.GetMonitorInsight:output_type -> proto.GetMonitorInsightResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_insight_proto_init() }
func file_proto_insight_proto_init() {
	if File_proto_insight_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_insight_proto_rawDesc), len(file_proto_insight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_insight_proto_goTypes,
		DependencyIndexes: file_proto_insight_proto_depIdxs,
		MessageInfos:      file_proto_insight_proto_msgTypes,
	}.Build()
	File_proto_insight_proto = out.File
	file_proto_insight_proto_goTypes = nil
	file_proto_insight_proto_depIdxs = nil
}
